#!/usr/bin/env bash
set -e

resolve_script_path() {
  local source="${BASH_SOURCE[0]}"
  while [[ -L "${source}" ]]; do
    local dir
    dir="$(cd -P "$(dirname "${source}")" && pwd)"
    source="$(readlink "${source}")"
    [[ "${source}" != /* ]] && source="${dir}/${source}"
  done
  cd -P "$(dirname "${source}")" && pwd
}

DIR="$(resolve_script_path)"

source "$DIR/src/common.sh"
source "$DIR/src/setup.sh"
source "$DIR/src/actions.sh"

COMMAND="${1:-help}"

case "$COMMAND" in
  install)
    action_install
    ;;
  link)
    action_link
    ;;
  restart)
    action_restart
    ;;
  status)
    action_status
    ;;
  help|--help|-h)
    action_help
    ;;
  *)
    echo "Unknown command: $COMMAND"
    action_help
    exit 1
    ;;
esac